import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ScreenSize } from "@/components/ScreenSize/ScreenSize";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className=" min-h-screen flex flex-col items-center">
          {children}
          <ScreenSize />
        </main>
        <Toaster />
      </body>
    </html>
  );
}
